name             'starter'
maintainer       'Kartik Null Cating-Subramanian'
maintainer_email 'ksubramanian@chef.io'
license          'All rights reserved'
description      'A basic starter cookbook'
version          '1.0.0'
